### PR TITLE
feat: support server mode

### PR DESCRIPTION
**Pull request by NitroCao**
Add support to run Trivy in client/server mode. When `SCANNER_TRIVY_REMOTE` is not empty, we'll run the Trivy with `client` subcommand.

Related issues: #76 #167

### CODE REVIEW

**Comment by NitroCao** [comment]
@danielpacak Hi guys, do you have any suggestion on this PR?

**Comment by danielpacak** [comment]
Could you explain why would you configure this adapter service in ClientServer mode? Are you using it with Harbor or in some other integration?

**Comment by NitroCao** [comment]
@danielpacak The efficiency of Trivy is quite slow when running in standalone mode, cause it can only scan one image at the same time. Refer to this issue https://github.com/aquasecurity/trivy/issues/650. So we need to run Trivy in client/server mode to speed up scanning.

**Comment by NitroCao** [comment]
The reason why increasing adapter replicas count is not a better way:
* If we run multiple adapters, each adapter needs to download vulnerability database from GitHub periodically. But if we run Trivy in client/server mode, only the Trivy server needs to download vulnerability database.
* Decrease the size of local cache. Because in client/server mode, only Trivy server holds cache data. So we may avoid such things like https://github.com/goharbor/harbor/issues/16606.
* Trivy now supports client/server mode, with which we can easily speed up scanning.
<br/>
<br/>

How do I plan installing Trivy server?
I would recommend to deploy Trivy server separately. Just run `trivy server --listen 0.0.0.0:4954 --cache-backend redis://myredis:6379`. The adapter then uses `trivy client` to scan images.  
<br>
<br>

> This code change without Trivy server installed along with Harbor is not very useful, is it?

Not always. I don't recommend that the Trivy server is bundled with Harbor. The documentation should indicate that if users want to run the adapter in client/server mode, they should deploy one Trivy server first.

This feature is optional, and is disabled by default. It's up to users to decide which mode to use. This PR is just to give those users like me a chance to run the adapter in client/server mode to speed up scanning.

**Comment by danielpacak** [comment]
As long as this features is not used by Harbor I'm very hesitant to maintain it even if the code is relatively simple. I think it should be discussed with Harbor community before we add it to this adapter service.

**Pull request closed without merging**
