### PR TITLE
Bump trivy to 0.17.2

### PR DESCRIPTION
**Pull request by dasmfm**
It would be great to release new version of adapter according to fresh Trivy release.

### CODE REVIEW

**Review by danielpacak — APPROVED** [review]
LGTM Thank you @dasmfm !

**Comment by borisklimenkovgr** [comment]
@danielpacak Could you please also bump version to use it in Harbor makefile?

**Comment by dasmfm** [comment]
@danielpacak Could you please also bump version to use it in Harbor makefile?

**Comment by danielpacak** [comment]
> @danielpacak Could you please also bump version to use it in Harbor makefile?

@dasmfm Here's the PR to follow up https://github.com/goharbor/harbor/pull/14797

**Pull request merged**
