### PR TITLE
Add deprecation message to readme

### PR DESCRIPTION
**Pull request by reasonerjt**

### CODE REVIEW

**Comment by knqyf263** [comment]
What if transferring the repository rather than a fork? Then GitHub automatically redirects aquasecurity/harbor-scanner-trivy to goharbor/harbor-scanner-trivy.

**Comment by reasonerjt** [comment]
@knqyf263 

Thanks for taking a look.

I slightly prefer forking, b/c I wanna make some break changes to the main branch, and if there are users or developers who don't like it, they can refer to the old repo.  (btw, I hope we can keep this repo for a while, but we don't expect any changes)

Let me know your thoughts.

**Comment by knqyf263** [comment]
>if there are users or developers who don't like it, they can refer to the old repo

In that case, users can keep using the older releases. I'm just curious how users will benefit from two repositories. However, if you prefer a fork, I'm fine with that. It's up to you.

**Comment by reasonerjt** [comment]
> However, if you prefer a fork, I'm fine with that. It's up to you.
Yep.

**Pull request merged**
