### PR TITLE
Added the --skip_java_update parameter

### PR DESCRIPTION
**Pull request by huansinho**
Added the --skip_java_update parameter to skip java db update

### CODE REVIEW

**Comment by chen-keinan** [comment]
@huansinho do you mind rebase your PR with upstream

**Comment by huansinho** [comment]
@chen-keinan This parameter is present in Trivy, just not in this plugin

**Comment by chen-keinan** [comment]
@huansinho I know , your PR has conflict with upstream therefore I need you to rebase

**Comment by chen-keinan** [comment]
Closing , duplicate to #419

**Pull request closed without merging**
