### PR TITLE
default security-checks flag to vuln and allow it to be tuned via env var

### PR DESCRIPTION
**Pull request by dkulchinsky**
`--security-check` flag will default to `vuln` to avoid scanning for `secrets`

can be tuned via `SCANNER_TRIVY_SECURITY_CHECKS` env variable

fixes https://github.com/goharbor/harbor/issues/17525

### CODE REVIEW

**Comment by dkulchinsky** [comment]
is anyone interested to take a look at this? @danielpacak?

**Comment by dkulchinsky** [comment]
@CLAassistant pushed the changes as requested, hopefully that does the trick 😄

**Comment by chen-keinan** [comment]
> @chen-keinan pushed the changes as requested, hopefully that does the trick 😄

Great , tests are passing now.
- I'll have to get another PR to fix vulnerabilities (as vulnerabilities found on this image , therefore it failing)
- I'll ping you once it done and you could rebase your PR and then we will get another release.

**Comment by chen-keinan** [comment]
@dkulchinsky since the `harbor-scanner-trivy` is based in `trivy` image then we need to wait for this [PR](https://github.com/aquasecurity/trivy/pull/2940) to be merged at `trivy` , I will push it ASAP.

**Comment by dkulchinsky** [comment]
thanks for the update @chen-keinan!

**Comment by chen-keinan** [comment]
@dkulchinsky vulnerability issue has ben fixed , can you please rebase you branch with upstream.

**Comment by dkulchinsky** [comment]
Hey @chen-keinan 👋🏼 everything seem to be in order now 👍🏼 thanks for the help!

**Review by chen-keinan — APPROVED** [review]

**Comment by chen-keinan** [comment]
LGTM 🚀

**Pull request merged**
